#!/usr/bin/env bash
CAQTDM_BIN="/APSshare/bin/caQtDM"
SCRIPT_DIR=`dirname ${BASH_SOURCE:-$0}`
MOTOR_UI_DIRS="/APSshare/epics/synApps_6_3/support/motor-R7-3-1/motorApp/op/ui/:/APSshare/epics/synApps_6_3/support/motor-R7-3-1/motorApp/op/ui/autoconvert/"
ASYN_UI_DIRS="/APSshare/epics/synApps_6_3/support/asyn-R4-44-2/opi/caqtdm/autoconvert/:/APSshare/epics/synApps_6_3/support/asyn-R4-44-2/opi/caqtdm/"
export CAQTDM_DISPLAY_PATH="${SCRIPT_DIR}/../../xeryonApp/op/ui/autoconvert/:${MOTOR_UI_DIRS}:${ASYN_UI_DIRS}"

${CAQTDM_BIN} -macro "P=xeryonExample:,M=m1,R=asyn_1" xeryon_admin.ui
